pipeline:

  start:
    image: docker
    secrets: [ MYSQL_ROOT_PASSWORD ]
    commands: 
      - docker run --name mysql-test -e MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} -e MYSQL_DATABASE=${MYSQL_DATABASE} mysql:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: [master, development]
      event: push

  test:
    image: docker
    secrets: [ MYSQL_ROOT_PASSWORD ]
    commands:
      - docker exec mysql-test mysql -e "show databases" -u root --password=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: [master, development]
      event: push

  delete:
    image: docker
    commands:
      - sh ./scripts/rm-d.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: [master, development]
      event: push
